In [1]:
import pandas as pd

In [2]:
data_one = {'A': ['A0', 'A1', 'A2', 'A3'],'B': ['B0', 'B1', 'B2', 'B3']}

In [3]:
data_two = {'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}

In [4]:
one = pd.DataFrame(data_one)

In [5]:
two = pd.DataFrame(data_two)

In [6]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [8]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

Let's get a single dataframe with 4 columns (since the index is same):

In [11]:
pd.concat([one,two],axis=1)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [12]:
pd.concat([two,one],axis=1)

    C   D   A   B
0  C0  D0  A0  B0
1  C1  D1  A1  B1
2  C2  D2  A2  B2
3  C3  D3  A3  B3

In [14]:
df = pd.concat([one,two],axis=0)

In [16]:
df.fillna('-')

    A   B   C   D
0  A0  B0   -   -
1  A1  B1   -   -
2  A2  B2   -   -
3  A3  B3   -   -
0   -   -  C0  D0
1   -   -  C1  D1
2   -   -  C2  D2
3   -   -  C3  D3

Not in lecture, but let's try giving index to the above df

In [23]:
df.index = range(0,8)

In [24]:
df

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
4  NaN  NaN   C0   D0
5  NaN  NaN   C1   D1
6  NaN  NaN   C2   D2
7  NaN  NaN   C3   D3

Let's try giving the index, but not manually

In [25]:
len(df)

8

In [33]:
df.index = range(0,len(df))

In [34]:
df

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
4  NaN  NaN   C0   D0
5  NaN  NaN   C1   D1
6  NaN  NaN   C2   D2
7  NaN  NaN   C3   D3

If we want the index to start from 1 instead of zero:

In [37]:
df.index = range(1,len(df)+1)

In [38]:
df

     A    B    C    D
1   A0   B0  NaN  NaN
2   A1   B1  NaN  NaN
3   A2   B2  NaN  NaN
4   A3   B3  NaN  NaN
5  NaN  NaN   C0   D0
6  NaN  NaN   C1   D1
7  NaN  NaN   C2   D2
8  NaN  NaN   C3   D3

### Instead of getting NaN, let's try shifting C0,C1... and D0,D1... below A and B:

In [39]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [40]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [41]:
two.columns = one.columns

In [44]:
two

    A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

What we did as changed the column of 'two' to be same as that of 'one'

Now, since the column names match up, we can proceed:

In [45]:
df = pd.concat([one,two],axis=0)

In [46]:
df

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3